name: Python CI with PyInstaller, Flake8, Black, and Isort

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
          pipenv install --dev

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --ignore=E402,W503 .

      - name: Format code with black
        run: |
          pip install black
          black --check .

      - name: Sort imports with isort
        run: |
          pip install isort
          pipenv run isort --check --profile black .

      - name: Checks code for missing docstrings
        run: |
          pip install interrogate
          pipenv run interrogate -vv .

      - name: Package the script using PyInstaller
        run: |
          .\build.bat

      - name: Upload PyInstaller Executable
        uses: actions/upload-artifact@v3
        with:
          name: packaged-script
          path: |
            dist/reviseur.exe
            dist/param.xml
            dist/images


